[tool.poetry]
name = "et-demo"
version = "0.1.0"
description = ""
package-mode = false
authors = ["killpopmusic <tomek.talarczyk@gmail.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.12,<4.0.0"
opencv-python = ">=4.10.0.84"
mediapipe = ">=0.10.20"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
